config/routes.rb
Rails.application.routes.draw do
  resources :matchings
  resources :restaurants
  root 'home#index'

  devise_for :users
  # resources :restaurant
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/affair.rb
class Affair < ApplicationRecord
  belongs_to :user, foreign_key: 'first_person_id', class_name: 'User'
  belongs_to :second_user, foreign_key: 'second_person_id', class_name: 'User'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages
  has_many :chat_users
  has_many :users, through: :chat_users
end

app/models/chat_user.rb
class ChatUser < ApplicationRecord
  belongs_to :user
  belongs_to :chat
end

app/models/matching.rb
class Matching < ApplicationRecord
  has_many :meals_names

  has_many :matching_meals
  has_many :meals, through: :matching_meals

  has_many :matching_restaurants
  has_many :restaurants, through: :matching_restaurants

  has_many :matching_users
  has_many :users, through: :matching_users
  has_and_belongs_to_many :matchings,
    classname: 'Matching',
    join_table: 'similar_matchings',
    association_foreign_key: 'similar_matching_id'

end

app/models/matching_user.rb
class MatchingUser < ApplicationRecord
  belongs_to :matching
  belongs_to :user
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_many :meal_sizes
  belongs_to :restaurant
end

app/models/meal_size.rb
class MealSize < ApplicationRecord
  belongs_to :meal
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat
end

app/models/opening_closing.rb
class OpeningClosing < ApplicationRecord
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_one :opening_closing
  has_many :user_restaurans
  has_many :users, through: :user_restaurants
  has_many :meals

  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :affairs, foreign_key: 'first_person_id', class_name: 'Affair'
  has_many :users, through: :affairs
  has_many :chat_users
  has_many :chats, through: :chat_users
  has_many :user_restaurans
  has_many :restaurants, through: :user_restaurans
  has_many :matching_users
  has_many :matchings, through: :matching_users
end

app/models/user_restaurant.rb
class UserRestaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/matchings_controller.rb
class MatchingsController < ApplicationController
  before_action :set_matching, only: [:show, :edit, :update, :destroy]

  # GET /matchings
  # GET /matchings.json
  def index
    @matchings = Matching.all
  end

  # GET /matchings/1
  # GET /matchings/1.json
  def show
  end

  # GET /matchings/new
  def new
    @matching = Matching.new
  end

  # GET /matchings/1/edit
  def edit
  end

  # POST /matchings
  # POST /matchings.json
  def create
    @matching = Matching.new(matching_params)

    respond_to do |format|
      if @matching.save
        format.html { redirect_to @matching, notice: 'Matching was successfully created.' }
        format.json { render :show, status: :created, location: @matching }
      else
        format.html { render :new }
        format.json { render json: @matching.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matchings/1
  # PATCH/PUT /matchings/1.json
  def update
    respond_to do |format|
      if @matching.update(matching_params)
        format.html { redirect_to @matching, notice: 'Matching was successfully updated.' }
        format.json { render :show, status: :ok, location: @matching }
      else
        format.html { render :edit }
        format.json { render json: @matching.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matchings/1
  # DELETE /matchings/1.json
  def destroy
    @matching.destroy
    respond_to do |format|
      format.html { redirect_to matchings_url, notice: 'Matching was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_matching
      @matching = Matching.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def matching_params
      params.fetch(:matching, {})
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.paginate(page: params[:page], per_page: 12)
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :pyszne_address, :picture_address, :meal_type, :city, :street, :zip_code, :website, :category, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_pln price
    (price / 100.0).to_s.gsub(/\.0$/, ' ') + ' zł'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matchings_helper.rb
module MatchingsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def pyszne_link link
    'http://pyszne.pl/' + link
  end

  def todays_opening_closing restaurant, day_number = Time.now.wday.to_i
    days = %w(mo tu we th fr sa su)
    opening_closing = restaurant.opening_closing
    opening = opening_closing[days[day_number] + '_opening']
    closing = opening_closing[days[day_number] + '_closing']
    opening + ' - ' + closing
  end

  def range_of_prices restaurant
    cheapest, *_ , most_expensive = restaurant
      .meals.map(&:meal_sizes).flatten.pluck(:cost).sort
    get_pln(cheapest) << ' - ' << get_pln(most_expensive)
  end

  def range_of_meal_prices meal, small_devices = false
     costs = meal.meal_sizes.pluck(:cost).sort
     cheapest = costs[0]
     the_most_expensive = costs[-1]

     if cheapest == the_most_expensive
        return get_pln(cheapest)
      else
        if small_devices
          return get_pln(cheapest) + ' +'
        else
          return get_pln(cheapest) + ' - ' + get_pln(the_most_expensive)
        end
      end
  end

  def meal_size_fix_name name
    (name == 'Normal' or name.blank?) ? 'Standardowa porcja' : name
  end

end

app/views/home/index.html.haml
.js-vue-bing-map
  -# #js-bing-map{style:"height:400px; witdh:400px", 'v-on:click': 'downloadMicrosoft'}
  #js-bing-map{style:"height:400px; witdh:400px", 'v-on:click': 'createHandler'}

-# .preloader-wrapper.big.active
-#   .spinner-layer.spinner-red-only
-#     .circle-clipper.left
-#       .circle
-#     .gap-patch
-#       .circle
-#     .circle-clipper.right
-#       .circle

-# #example
-#   %vue-loading-circle-componet{'loading': "active"}

app/views/matchings/_form.html.haml
= form_for @matching do |f|
  - if @matching.errors.any?
    #error_explanation
      %h2= "#{pluralize(@matching.errors.count, "error")} prohibited this matching from being saved:"
      %ul
        - @matching.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/matchings/edit.html.haml
%h1 Editing matching

= render 'form'

= link_to 'Show', @matching
\|
= link_to 'Back', matchings_path

app/views/matchings/index.html.haml
%h1 Listing matchings

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @matchings.each do |matching|
      %tr
        %td= link_to 'Show', matching
        %td= link_to 'Edit', edit_matching_path(matching)
        %td= link_to 'Destroy', matching, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Matching', new_matching_path

app/views/matchings/new.html.haml
%h1 New matching

= render 'form'

= link_to 'Back', matchings_path

app/views/matchings/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_matching_path(@matching)
\|
= link_to 'Back', matchings_path

app/views/restaurants/_form.html.haml
= form_for @restaurant do |f|
  - if @restaurant.errors.any?
    #error_explanation
      %h2= "#{pluralize(@restaurant.errors.count, "error")} prohibited this restaurant from being saved:"
      %ul
        - @restaurant.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :pyszne_address
    = f.text_field :pyszne_address
  .field
    = f.label :picture_address
    = f.text_field :picture_address
  .field
    = f.label :meal_type
    = f.text_field :meal_type
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :street
    = f.text_field :street
  .field
    = f.label :zip_code
    = f.text_field :zip_code
  .field
    = f.label :website
    = f.text_field :website
  .field
    = f.label :category
    = f.text_field :category
  .field
    = f.label :latitude
    = f.text_field :latitude
  .field
    = f.label :longitude
    = f.text_field :longitude
  .actions
    = f.submit 'Save'

app/views/restaurants/edit.html.haml
%h1 Editing restaurant

= render 'form'

= link_to 'Show', @restaurant
\|
= link_to 'Back', restaurants_path

app/views/restaurants/index.html.haml
.row
  - @restaurants.each do |restaurant|


    .card.col.s12.m6.l4.center
      .card-image.card-horizontal.waves-effect.waves-block.waves-light
        %img.activator{:src => restaurant.image.url}/
      .card-content
        %span.card-title.activator.grey-text.text-darken-4
          =link_to restaurant_path(restaurant) do
            .truncate.black-text
              = restaurant.name
          -#
        .card-action
          %p
            %a{:href => "#"} This is a link
      .card-reveal
        %span.card-title.grey-text.text-darken-4
          %i.material-icons.right close
          = link_to restaurant_path(restaurant), class: 'black-text' do
            = restaurant.name
        %p
          = restaurant.meal_type
        %p
          = restaurant.street
        %p




.col-xs-12
  = will_paginate @posts
.col-xs-12
  = link_to I18n.t('restaurant.report_new'), new_restaurant_path

app/views/restaurants/new.html.haml
%h1 New restaurant

= render 'form'

= link_to 'Back', restaurants_path

app/views/restaurants/partials/_comments.haml
#disqus_thread
:javascript
  (function() { // DON'T EDIT BELOW THIS LINE
  var d = document, s = d.createElement('script');
  s.src = '//dont-eat-alone.disqus.com/embed.js';
  s.setAttribute('data-timestamp', +new Date());
  (d.head || d.body).appendChild(s);
  })();

app/views/restaurants/partials/_informations.haml
%table.striped.centered.responsive-table
  %tbody
    %tr
      %td
        = t('miscellaneous.name')
      %td
        = @restaurant.name
    %tr
      %td
        = t('miscellaneous.city')
      %td
        = @restaurant.city
    %tr
      %td
        = t('miscellaneous.street')
      %td
        = @restaurant.street
    %tr
      %td
        = t('miscellaneous.meal_type')
      %td
        = @restaurant.meal_type
    %tr
      %td
        = t('miscellaneous.category')
      %td
        = @restaurant.category
    - %w(mo tu we th fr sa su).each.with_index do |day, indx|
      %tr
        %td
          = t("miscellaneous.#{day}")
        %td
          = todays_opening_closing @restaurant, indx
    %tr
      %td
        = t('miscellaneous.prices')
      %td
        = range_of_prices @restaurant

app/views/restaurants/partials/_menu.haml
%ul.collapsible{'data-collapsible': 'accordion'}
  - @restaurant.meals.each do |meal|
    %li
      .collapsible-header
        = meal.name
        %span.badge
          .hide-on-small-only
            = range_of_meal_prices(meal)
      .collapsible-body
        - if meal.description.present?
          %p
            = meal.description
        %p
          -meal.meal_sizes.each do |meal_size|
            = "#{meal_size_fix_name(meal_size.name)} -- #{get_pln(meal_size.cost)}"
            %br

app/views/restaurants/show.html.haml
.row
  .col.s12.l6
    %h2.header
      = @restaurant.name
    .card.horizontal
      .card-image
        %img{:src => @restaurant.image.url}/
      .card-stacked
        .card-content
          %p
            = @restaurant.meal_type
          .hide-on-small-only
            %p
              = todays_opening_closing @restaurant
            %p
              = range_of_prices @restaurant
        .card-action
          = link_to t('miscellaneous.pyszne_pl'), pyszne_link(@restaurant.pyszne_address)
          = link_to t('miscellaneous.website'), @restaurant.website if @restaurant.website

.row
  .col.s12
    %ul.tabs.tabs-fixed-width
      %li.tab.col.s3
        %a{:href => "#dea-restaurant-show-partial-informations"}
          %i.fa.fa-info

      %li.tab.col.s3
        %a.active{:href => "#dea-restaurant-show-partial-menu"}
          %i.fa.fa-list

      %li.tab.col.s3
        %a{:href => "#dea-restaurant-show-partial-comments"}
          %i.fa.fa-comments-o

      %li.tab.col.s3
        %a{:href => "#dea-restaurant-show-partial-matchings"}
          %i.fa.fa-users

    #dea-restaurant-show-partial-informations.col.s12
      = render partial: 'restaurants/partials/informations'
    #dea-restaurant-show-partial-menu.col.s12
      = render 'restaurants/partials/menu'
    #dea-restaurant-show-partial-comments.col.s12
      = render 'restaurants/partials/comments'
    #dea-restaurant-show-partial-matchings.col.s12
      = render 'restaurants/partials/matchings'

= link_to 'Edit', edit_restaurant_path(@restaurant)
\|
= link_to 'Back', restaurants_path